services:
  db:
    image: postgres:16-alpine
    container_name: app_db
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: appdb
    ports: ["5432:5432"]
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    build: { context: . }
    container_name: app_backend
    working_dir: /app
    command: sh -lc "sh ./gradlew bootRun --no-daemon"
    volumes:
      - ./:/app
    environment:
      GRADLE_USER_HOME: /tmp/gradle
      SPRING_PROFILES_ACTIVE: dev
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/appdb
      SPRING_DATASOURCE_USERNAME: app
      SPRING_DATASOURCE_PASSWORD: app
    ports: ["8080:8080"]
    depends_on:
      - db

volumes:
  db_data:
