spring:
  application:
    name: fitbyte

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/appdb}
    username: ${SPRING_DATASOURCE_USERNAME:app}
    password: ${SPRING_DATASOURCE_PASSWORD:app}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: true
    locations: classpath:db/migration
    default-schema: public
    clean-disabled: true
    baseline-on-migrate: true

server:
  port: 8080

jwt:
  secret: ${JWT_SECRET:Uzl3YSBoYXZlIGEgc2VjcmV0IGtleSB0aGF0IGlzIHZlcnkgbG9uZyBhbmQgc2VjdXJl}

logging:
  level:
    org.flywaydb: INFO
    org.springframework.boot.autoconfigure: INFO

minio:
  endpoint: ${MINIO_ENDPOINT:http://minio:9000}
  publicEndpoint: ${MINIO_PUBLIC_ENDPOINT:http://localhost:9000}
  accessKey: ${MINIO_ACCESS_KEY:kopi}
  secretKey: ${MINIO_SECRET_KEY:passwordkopi}
  bucket: ${MINIO_BUCKET:uploads}
  region: ${MINIO_REGION:us-east-1}
  secure: ${MINIO_SECURE:false}
  presign-expiry-seconds: ${MINIO_PRESIGN_EXPIRY_SECONDS:3600}